"""Add plan column

Revision ID: a67ae6271157
Revises: 0e657b5c2fff
Create Date: 2026-07-23 17:30:44.439232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a67ae6271157'
down_revision: Union[str, None] = '0e657b5c2fff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('plan', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'plan')
    # ### end Alembic commands ###
